# Site settings
title: Fluidity
email: fluidity@imperial.ac.uk
description: The Fluidity computational fluid dynamics project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

twitter_username: AMCG_Imperial
github_username: fluidityproject

# Build settings
markdown: kramdown
